### config | tmux | ishan kunam ###

# -------------
#    general
# -------------

# set default prefix
# ctrl + b

# set default index
set -g base-index 0
setw -g pane-base-index 0

# renumber windows automatically when one is closed
set -g renumber-windows on

# increase scrollback buffer limit
set -g history-limit 10000

# reduce escape-time (needed for neovim)
set -sg escape-time 10

# enable focus events (needed for autoread in neovim)
set -g focus-events on

# allow tmux to set the terminal title
set -g set-titles on
set -g set-titles-string '#S'

# set mouse support
set -g mouse on

# ----------------
#    appearance
# ----------------

# tell tmux it's running inside a 256-color terminal
set -g default-terminal "tmux-256color"

# enable true color (i.e., 24-bit) passthrough to Ghostty
set -ag terminal-overrides ",ghostty:RGB"

# configure left status
# (session name)
set -g status-left-length 30

# configure right status
# (time)
set -g status-right-length 20

# --------------
#    keybinds
# --------------

# set keybind to reload config
bind r source-file ~/.tmux.conf \; display-message "config reloaded"

# set keybonds to split panes
# (-c "#{pane_current_path}" opens the new pane in the same directory)
# vertical split
bind | split-window -h -c "#{pane_current_path}"
# horizontal split
bind - split-window -v -c "#{pane_current_path}"
unbind %
unbind '"'

# set keybind to open new window
# (-c "#{pane_current_path}" opens the new pane in the same directory)
bind c new-window -c "#{pane_current_path}"

# set keybinds for pane navigation in vim-style (i.e., hjkl)
# move left
bind h select-pane -L
# move down
bind j select-pane -D
# move up
bind k select-pane -U
# move right
bind l select-pane -R

# set keybinds to resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# ---------------
#    copy mode
# ---------------

# set keybinds in copy mode to vim-style
# enter copy mode w/ ctrl + [
# exit copy mode w/ q
setw -g mode-keys vi

# set v to begin selection
bind -T copy-mode-vi v send-keys -X begin-selection

# set y to yank to macOS clipboard (via pbcopy)
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# ensure drag to select with mouse pipes to macOS clipboard (via pbcopy)
# (mouse is currently ON)
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"